remote_theme: pages-themes/minimal@v0.2.0
show_downloads: false
title: [Shixian GENG]
description: [HCI/Mobile Health PhD@UTokyo]
logo: IMG.jpg
github:
  github.owner_url: https://iis-lab.org/
  another_url: Interactive Intelligent Systems Laboratory
